components:
  parameters:
    itemKey:
      in: path
      name: itemKey
      required: true
      schema:
        type: string
      description: The item's primary key.
      examples:
        example-OK:
          value: 100
        example-404:
          value: -1
    tag:
      in: query
      name: tag
      schema:
        type: string
      description: Comma-separated list of keywords.
      required: true
      default: tag1,tag2
